// Code generated by protoc-gen-go.
// source: pkg/protobuf/app/app.proto
// DO NOT EDIT!

/*
Package app is a generated protocol buffer package.

It is generated from these files:
	pkg/protobuf/app/app.proto

It has these top-level messages:
	CreateRequest
	ListResponse
	LogsRequest
	LogsResponse
	InfoRequest
	InfoResponse
	SetEnvRequest
	UnsetEnvRequest
	SetSecretRequest
	SetAutoscaleRequest
	SetReplicasRequest
	DeleteRequest
	DeletePodsRequest
	ChangeTeamRequest
	SetVHostsRequest
	SetAdditionalLabelsRequest
	Empty
*/
package app

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateRequest struct {
	Name             string                   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Team             string                   `protobuf:"bytes,2,opt,name=team" json:"team,omitempty"`
	ProcessType      string                   `protobuf:"bytes,3,opt,name=process_type,json=processType" json:"process_type,omitempty"`
	Limits           *CreateRequest_Limits    `protobuf:"bytes,4,opt,name=limits" json:"limits,omitempty"`
	Autoscale        *CreateRequest_Autoscale `protobuf:"bytes,5,opt,name=autoscale" json:"autoscale,omitempty"`
	VirtualHost      string                   `protobuf:"bytes,6,opt,name=virtual_host,json=virtualHost" json:"virtual_host,omitempty"`
	Internal         bool                     `protobuf:"varint,7,opt,name=internal" json:"internal,omitempty"`
	Protocol         string                   `protobuf:"bytes,8,opt,name=protocol" json:"protocol,omitempty"`
	ReserveStaticIp  bool                     `protobuf:"varint,9,opt,name=reserve_static_ip,json=reserveStaticIp" json:"reserve_static_ip,omitempty"`
	AdditionalLabels map[string]string        `protobuf:"bytes,10,rep,name=additional_labels,json=additionalLabels" json:"additional_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRequest) GetTeam() string {
	if m != nil {
		return m.Team
	}
	return ""
}

func (m *CreateRequest) GetProcessType() string {
	if m != nil {
		return m.ProcessType
	}
	return ""
}

func (m *CreateRequest) GetLimits() *CreateRequest_Limits {
	if m != nil {
		return m.Limits
	}
	return nil
}

func (m *CreateRequest) GetAutoscale() *CreateRequest_Autoscale {
	if m != nil {
		return m.Autoscale
	}
	return nil
}

func (m *CreateRequest) GetVirtualHost() string {
	if m != nil {
		return m.VirtualHost
	}
	return ""
}

func (m *CreateRequest) GetInternal() bool {
	if m != nil {
		return m.Internal
	}
	return false
}

func (m *CreateRequest) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *CreateRequest) GetReserveStaticIp() bool {
	if m != nil {
		return m.ReserveStaticIp
	}
	return false
}

func (m *CreateRequest) GetAdditionalLabels() map[string]string {
	if m != nil {
		return m.AdditionalLabels
	}
	return nil
}

type CreateRequest_Limits struct {
	Default        []*CreateRequest_Limits_LimitRangeQuantity `protobuf:"bytes,1,rep,name=default" json:"default,omitempty"`
	DefaultRequest []*CreateRequest_Limits_LimitRangeQuantity `protobuf:"bytes,2,rep,name=default_request,json=defaultRequest" json:"default_request,omitempty"`
}

func (m *CreateRequest_Limits) Reset()                    { *m = CreateRequest_Limits{} }
func (m *CreateRequest_Limits) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest_Limits) ProtoMessage()               {}
func (*CreateRequest_Limits) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *CreateRequest_Limits) GetDefault() []*CreateRequest_Limits_LimitRangeQuantity {
	if m != nil {
		return m.Default
	}
	return nil
}

func (m *CreateRequest_Limits) GetDefaultRequest() []*CreateRequest_Limits_LimitRangeQuantity {
	if m != nil {
		return m.DefaultRequest
	}
	return nil
}

type CreateRequest_Limits_LimitRangeQuantity struct {
	Quantity string `protobuf:"bytes,1,opt,name=quantity" json:"quantity,omitempty"`
	Resource string `protobuf:"bytes,2,opt,name=resource" json:"resource,omitempty"`
}

func (m *CreateRequest_Limits_LimitRangeQuantity) Reset() {
	*m = CreateRequest_Limits_LimitRangeQuantity{}
}
func (m *CreateRequest_Limits_LimitRangeQuantity) String() string { return proto.CompactTextString(m) }
func (*CreateRequest_Limits_LimitRangeQuantity) ProtoMessage()    {}
func (*CreateRequest_Limits_LimitRangeQuantity) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0, 0}
}

func (m *CreateRequest_Limits_LimitRangeQuantity) GetQuantity() string {
	if m != nil {
		return m.Quantity
	}
	return ""
}

func (m *CreateRequest_Limits_LimitRangeQuantity) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

type CreateRequest_Autoscale struct {
	CpuTargetUtilization int32 `protobuf:"varint,1,opt,name=cpu_target_utilization,json=cpuTargetUtilization" json:"cpu_target_utilization,omitempty"`
	Max                  int32 `protobuf:"varint,2,opt,name=max" json:"max,omitempty"`
	Min                  int32 `protobuf:"varint,3,opt,name=min" json:"min,omitempty"`
}

func (m *CreateRequest_Autoscale) Reset()                    { *m = CreateRequest_Autoscale{} }
func (m *CreateRequest_Autoscale) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest_Autoscale) ProtoMessage()               {}
func (*CreateRequest_Autoscale) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func (m *CreateRequest_Autoscale) GetCpuTargetUtilization() int32 {
	if m != nil {
		return m.CpuTargetUtilization
	}
	return 0
}

func (m *CreateRequest_Autoscale) GetMax() int32 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *CreateRequest_Autoscale) GetMin() int32 {
	if m != nil {
		return m.Min
	}
	return 0
}

type ListResponse struct {
	Apps []*ListResponse_App `protobuf:"bytes,1,rep,name=apps" json:"apps,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ListResponse) GetApps() []*ListResponse_App {
	if m != nil {
		return m.Apps
	}
	return nil
}

type ListResponse_App struct {
	Team string   `protobuf:"bytes,1,opt,name=team" json:"team,omitempty"`
	Name string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Urls []string `protobuf:"bytes,3,rep,name=urls" json:"urls,omitempty"`
}

func (m *ListResponse_App) Reset()                    { *m = ListResponse_App{} }
func (m *ListResponse_App) String() string            { return proto.CompactTextString(m) }
func (*ListResponse_App) ProtoMessage()               {}
func (*ListResponse_App) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *ListResponse_App) GetTeam() string {
	if m != nil {
		return m.Team
	}
	return ""
}

func (m *ListResponse_App) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListResponse_App) GetUrls() []string {
	if m != nil {
		return m.Urls
	}
	return nil
}

type LogsRequest struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Lines     int64  `protobuf:"varint,2,opt,name=lines" json:"lines,omitempty"`
	Follow    bool   `protobuf:"varint,3,opt,name=follow" json:"follow,omitempty"`
	PodName   string `protobuf:"bytes,4,opt,name=pod_name,json=podName" json:"pod_name,omitempty"`
	Previous  bool   `protobuf:"varint,5,opt,name=previous" json:"previous,omitempty"`
	Container string `protobuf:"bytes,6,opt,name=container" json:"container,omitempty"`
}

func (m *LogsRequest) Reset()                    { *m = LogsRequest{} }
func (m *LogsRequest) String() string            { return proto.CompactTextString(m) }
func (*LogsRequest) ProtoMessage()               {}
func (*LogsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LogsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LogsRequest) GetLines() int64 {
	if m != nil {
		return m.Lines
	}
	return 0
}

func (m *LogsRequest) GetFollow() bool {
	if m != nil {
		return m.Follow
	}
	return false
}

func (m *LogsRequest) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *LogsRequest) GetPrevious() bool {
	if m != nil {
		return m.Previous
	}
	return false
}

func (m *LogsRequest) GetContainer() string {
	if m != nil {
		return m.Container
	}
	return ""
}

type LogsResponse struct {
	Text string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
}

func (m *LogsResponse) Reset()                    { *m = LogsResponse{} }
func (m *LogsResponse) String() string            { return proto.CompactTextString(m) }
func (*LogsResponse) ProtoMessage()               {}
func (*LogsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LogsResponse) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type InfoRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *InfoRequest) Reset()                    { *m = InfoRequest{} }
func (m *InfoRequest) String() string            { return proto.CompactTextString(m) }
func (*InfoRequest) ProtoMessage()               {}
func (*InfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *InfoRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type InfoResponse struct {
	Team      string                  `protobuf:"bytes,1,opt,name=team" json:"team,omitempty"`
	Addresses []*InfoResponse_Address `protobuf:"bytes,2,rep,name=addresses" json:"addresses,omitempty"`
	EnvVars   []*InfoResponse_EnvVar  `protobuf:"bytes,3,rep,name=env_vars,json=envVars" json:"env_vars,omitempty"`
	Status    *InfoResponse_Status    `protobuf:"bytes,4,opt,name=status" json:"status,omitempty"`
	Autoscale *InfoResponse_Autoscale `protobuf:"bytes,5,opt,name=autoscale" json:"autoscale,omitempty"`
	Limits    *InfoResponse_Limits    `protobuf:"bytes,6,opt,name=limits" json:"limits,omitempty"`
	Protocol  string                  `protobuf:"bytes,7,opt,name=protocol" json:"protocol,omitempty"`
	Volumes   []string                `protobuf:"bytes,8,rep,name=volumes" json:"volumes,omitempty"`
}

func (m *InfoResponse) Reset()                    { *m = InfoResponse{} }
func (m *InfoResponse) String() string            { return proto.CompactTextString(m) }
func (*InfoResponse) ProtoMessage()               {}
func (*InfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *InfoResponse) GetTeam() string {
	if m != nil {
		return m.Team
	}
	return ""
}

func (m *InfoResponse) GetAddresses() []*InfoResponse_Address {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *InfoResponse) GetEnvVars() []*InfoResponse_EnvVar {
	if m != nil {
		return m.EnvVars
	}
	return nil
}

func (m *InfoResponse) GetStatus() *InfoResponse_Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *InfoResponse) GetAutoscale() *InfoResponse_Autoscale {
	if m != nil {
		return m.Autoscale
	}
	return nil
}

func (m *InfoResponse) GetLimits() *InfoResponse_Limits {
	if m != nil {
		return m.Limits
	}
	return nil
}

func (m *InfoResponse) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *InfoResponse) GetVolumes() []string {
	if m != nil {
		return m.Volumes
	}
	return nil
}

type InfoResponse_Address struct {
	Hostname string `protobuf:"bytes,1,opt,name=hostname" json:"hostname,omitempty"`
}

func (m *InfoResponse_Address) Reset()                    { *m = InfoResponse_Address{} }
func (m *InfoResponse_Address) String() string            { return proto.CompactTextString(m) }
func (*InfoResponse_Address) ProtoMessage()               {}
func (*InfoResponse_Address) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

func (m *InfoResponse_Address) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

type InfoResponse_EnvVar struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *InfoResponse_EnvVar) Reset()                    { *m = InfoResponse_EnvVar{} }
func (m *InfoResponse_EnvVar) String() string            { return proto.CompactTextString(m) }
func (*InfoResponse_EnvVar) ProtoMessage()               {}
func (*InfoResponse_EnvVar) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 1} }

func (m *InfoResponse_EnvVar) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *InfoResponse_EnvVar) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type InfoResponse_Status struct {
	Cpu  int32                      `protobuf:"varint,1,opt,name=cpu" json:"cpu,omitempty"`
	Pods []*InfoResponse_Status_Pod `protobuf:"bytes,3,rep,name=pods" json:"pods,omitempty"`
}

func (m *InfoResponse_Status) Reset()                    { *m = InfoResponse_Status{} }
func (m *InfoResponse_Status) String() string            { return proto.CompactTextString(m) }
func (*InfoResponse_Status) ProtoMessage()               {}
func (*InfoResponse_Status) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 2} }

func (m *InfoResponse_Status) GetCpu() int32 {
	if m != nil {
		return m.Cpu
	}
	return 0
}

func (m *InfoResponse_Status) GetPods() []*InfoResponse_Status_Pod {
	if m != nil {
		return m.Pods
	}
	return nil
}

type InfoResponse_Status_Pod struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	State    string `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
	Age      int64  `protobuf:"varint,3,opt,name=age" json:"age,omitempty"`
	Restarts int32  `protobuf:"varint,4,opt,name=restarts" json:"restarts,omitempty"`
	Ready    bool   `protobuf:"varint,5,opt,name=ready" json:"ready,omitempty"`
}

func (m *InfoResponse_Status_Pod) Reset()                    { *m = InfoResponse_Status_Pod{} }
func (m *InfoResponse_Status_Pod) String() string            { return proto.CompactTextString(m) }
func (*InfoResponse_Status_Pod) ProtoMessage()               {}
func (*InfoResponse_Status_Pod) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 2, 0} }

func (m *InfoResponse_Status_Pod) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InfoResponse_Status_Pod) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *InfoResponse_Status_Pod) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *InfoResponse_Status_Pod) GetRestarts() int32 {
	if m != nil {
		return m.Restarts
	}
	return 0
}

func (m *InfoResponse_Status_Pod) GetReady() bool {
	if m != nil {
		return m.Ready
	}
	return false
}

type InfoResponse_Autoscale struct {
	CpuTargetUtilization int32 `protobuf:"varint,1,opt,name=cpu_target_utilization,json=cpuTargetUtilization" json:"cpu_target_utilization,omitempty"`
	Max                  int32 `protobuf:"varint,2,opt,name=max" json:"max,omitempty"`
	Min                  int32 `protobuf:"varint,3,opt,name=min" json:"min,omitempty"`
}

func (m *InfoResponse_Autoscale) Reset()                    { *m = InfoResponse_Autoscale{} }
func (m *InfoResponse_Autoscale) String() string            { return proto.CompactTextString(m) }
func (*InfoResponse_Autoscale) ProtoMessage()               {}
func (*InfoResponse_Autoscale) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 3} }

func (m *InfoResponse_Autoscale) GetCpuTargetUtilization() int32 {
	if m != nil {
		return m.CpuTargetUtilization
	}
	return 0
}

func (m *InfoResponse_Autoscale) GetMax() int32 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *InfoResponse_Autoscale) GetMin() int32 {
	if m != nil {
		return m.Min
	}
	return 0
}

type InfoResponse_Limits struct {
	Default        []*InfoResponse_Limits_LimitRangeQuantity `protobuf:"bytes,1,rep,name=default" json:"default,omitempty"`
	DefaultRequest []*InfoResponse_Limits_LimitRangeQuantity `protobuf:"bytes,2,rep,name=default_request,json=defaultRequest" json:"default_request,omitempty"`
}

func (m *InfoResponse_Limits) Reset()                    { *m = InfoResponse_Limits{} }
func (m *InfoResponse_Limits) String() string            { return proto.CompactTextString(m) }
func (*InfoResponse_Limits) ProtoMessage()               {}
func (*InfoResponse_Limits) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 4} }

func (m *InfoResponse_Limits) GetDefault() []*InfoResponse_Limits_LimitRangeQuantity {
	if m != nil {
		return m.Default
	}
	return nil
}

func (m *InfoResponse_Limits) GetDefaultRequest() []*InfoResponse_Limits_LimitRangeQuantity {
	if m != nil {
		return m.DefaultRequest
	}
	return nil
}

type InfoResponse_Limits_LimitRangeQuantity struct {
	Quantity string `protobuf:"bytes,1,opt,name=quantity" json:"quantity,omitempty"`
	Resource string `protobuf:"bytes,2,opt,name=resource" json:"resource,omitempty"`
}

func (m *InfoResponse_Limits_LimitRangeQuantity) Reset() {
	*m = InfoResponse_Limits_LimitRangeQuantity{}
}
func (m *InfoResponse_Limits_LimitRangeQuantity) String() string { return proto.CompactTextString(m) }
func (*InfoResponse_Limits_LimitRangeQuantity) ProtoMessage()    {}
func (*InfoResponse_Limits_LimitRangeQuantity) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{5, 4, 0}
}

func (m *InfoResponse_Limits_LimitRangeQuantity) GetQuantity() string {
	if m != nil {
		return m.Quantity
	}
	return ""
}

func (m *InfoResponse_Limits_LimitRangeQuantity) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

type SetEnvRequest struct {
	Name    string                  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	EnvVars []*SetEnvRequest_EnvVar `protobuf:"bytes,2,rep,name=env_vars,json=envVars" json:"env_vars,omitempty"`
}

func (m *SetEnvRequest) Reset()                    { *m = SetEnvRequest{} }
func (m *SetEnvRequest) String() string            { return proto.CompactTextString(m) }
func (*SetEnvRequest) ProtoMessage()               {}
func (*SetEnvRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SetEnvRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SetEnvRequest) GetEnvVars() []*SetEnvRequest_EnvVar {
	if m != nil {
		return m.EnvVars
	}
	return nil
}

type SetEnvRequest_EnvVar struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *SetEnvRequest_EnvVar) Reset()                    { *m = SetEnvRequest_EnvVar{} }
func (m *SetEnvRequest_EnvVar) String() string            { return proto.CompactTextString(m) }
func (*SetEnvRequest_EnvVar) ProtoMessage()               {}
func (*SetEnvRequest_EnvVar) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 0} }

func (m *SetEnvRequest_EnvVar) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SetEnvRequest_EnvVar) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type UnsetEnvRequest struct {
	Name    string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	EnvVars []string `protobuf:"bytes,2,rep,name=env_vars,json=envVars" json:"env_vars,omitempty"`
}

func (m *UnsetEnvRequest) Reset()                    { *m = UnsetEnvRequest{} }
func (m *UnsetEnvRequest) String() string            { return proto.CompactTextString(m) }
func (*UnsetEnvRequest) ProtoMessage()               {}
func (*UnsetEnvRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UnsetEnvRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UnsetEnvRequest) GetEnvVars() []string {
	if m != nil {
		return m.EnvVars
	}
	return nil
}

type SetSecretRequest struct {
	Name       string                       `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	SecretEnvs []*SetEnvRequest_EnvVar      `protobuf:"bytes,2,rep,name=secret_envs,json=secretEnvs" json:"secret_envs,omitempty"`
	SecretFile *SetSecretRequest_SecretFile `protobuf:"bytes,3,opt,name=secret_file,json=secretFile" json:"secret_file,omitempty"`
}

func (m *SetSecretRequest) Reset()                    { *m = SetSecretRequest{} }
func (m *SetSecretRequest) String() string            { return proto.CompactTextString(m) }
func (*SetSecretRequest) ProtoMessage()               {}
func (*SetSecretRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *SetSecretRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SetSecretRequest) GetSecretEnvs() []*SetEnvRequest_EnvVar {
	if m != nil {
		return m.SecretEnvs
	}
	return nil
}

func (m *SetSecretRequest) GetSecretFile() *SetSecretRequest_SecretFile {
	if m != nil {
		return m.SecretFile
	}
	return nil
}

type SetSecretRequest_SecretFile struct {
	Key     string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *SetSecretRequest_SecretFile) Reset()                    { *m = SetSecretRequest_SecretFile{} }
func (m *SetSecretRequest_SecretFile) String() string            { return proto.CompactTextString(m) }
func (*SetSecretRequest_SecretFile) ProtoMessage()               {}
func (*SetSecretRequest_SecretFile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8, 0} }

func (m *SetSecretRequest_SecretFile) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SetSecretRequest_SecretFile) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type SetAutoscaleRequest struct {
	Name      string                         `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Autoscale *SetAutoscaleRequest_Autoscale `protobuf:"bytes,2,opt,name=autoscale" json:"autoscale,omitempty"`
}

func (m *SetAutoscaleRequest) Reset()                    { *m = SetAutoscaleRequest{} }
func (m *SetAutoscaleRequest) String() string            { return proto.CompactTextString(m) }
func (*SetAutoscaleRequest) ProtoMessage()               {}
func (*SetAutoscaleRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *SetAutoscaleRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SetAutoscaleRequest) GetAutoscale() *SetAutoscaleRequest_Autoscale {
	if m != nil {
		return m.Autoscale
	}
	return nil
}

type SetAutoscaleRequest_Autoscale struct {
	CpuTargetUtilization int32 `protobuf:"varint,1,opt,name=cpu_target_utilization,json=cpuTargetUtilization" json:"cpu_target_utilization,omitempty"`
	Max                  int32 `protobuf:"varint,2,opt,name=max" json:"max,omitempty"`
	Min                  int32 `protobuf:"varint,3,opt,name=min" json:"min,omitempty"`
}

func (m *SetAutoscaleRequest_Autoscale) Reset()         { *m = SetAutoscaleRequest_Autoscale{} }
func (m *SetAutoscaleRequest_Autoscale) String() string { return proto.CompactTextString(m) }
func (*SetAutoscaleRequest_Autoscale) ProtoMessage()    {}
func (*SetAutoscaleRequest_Autoscale) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{9, 0}
}

func (m *SetAutoscaleRequest_Autoscale) GetCpuTargetUtilization() int32 {
	if m != nil {
		return m.CpuTargetUtilization
	}
	return 0
}

func (m *SetAutoscaleRequest_Autoscale) GetMax() int32 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *SetAutoscaleRequest_Autoscale) GetMin() int32 {
	if m != nil {
		return m.Min
	}
	return 0
}

type SetReplicasRequest struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Replicas int32  `protobuf:"varint,2,opt,name=replicas" json:"replicas,omitempty"`
}

func (m *SetReplicasRequest) Reset()                    { *m = SetReplicasRequest{} }
func (m *SetReplicasRequest) String() string            { return proto.CompactTextString(m) }
func (*SetReplicasRequest) ProtoMessage()               {}
func (*SetReplicasRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *SetReplicasRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SetReplicasRequest) GetReplicas() int32 {
	if m != nil {
		return m.Replicas
	}
	return 0
}

type DeleteRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *DeleteRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeletePodsRequest struct {
	Name      string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	PodsNames []string `protobuf:"bytes,2,rep,name=pods_names,json=podsNames" json:"pods_names,omitempty"`
}

func (m *DeletePodsRequest) Reset()                    { *m = DeletePodsRequest{} }
func (m *DeletePodsRequest) String() string            { return proto.CompactTextString(m) }
func (*DeletePodsRequest) ProtoMessage()               {}
func (*DeletePodsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *DeletePodsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeletePodsRequest) GetPodsNames() []string {
	if m != nil {
		return m.PodsNames
	}
	return nil
}

type ChangeTeamRequest struct {
	AppName  string `protobuf:"bytes,1,opt,name=app_name,json=appName" json:"app_name,omitempty"`
	TeamName string `protobuf:"bytes,2,opt,name=team_name,json=teamName" json:"team_name,omitempty"`
}

func (m *ChangeTeamRequest) Reset()                    { *m = ChangeTeamRequest{} }
func (m *ChangeTeamRequest) String() string            { return proto.CompactTextString(m) }
func (*ChangeTeamRequest) ProtoMessage()               {}
func (*ChangeTeamRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ChangeTeamRequest) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *ChangeTeamRequest) GetTeamName() string {
	if m != nil {
		return m.TeamName
	}
	return ""
}

type SetVHostsRequest struct {
	AppName string   `protobuf:"bytes,1,opt,name=app_name,json=appName" json:"app_name,omitempty"`
	Vhosts  []string `protobuf:"bytes,2,rep,name=vhosts" json:"vhosts,omitempty"`
}

func (m *SetVHostsRequest) Reset()                    { *m = SetVHostsRequest{} }
func (m *SetVHostsRequest) String() string            { return proto.CompactTextString(m) }
func (*SetVHostsRequest) ProtoMessage()               {}
func (*SetVHostsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *SetVHostsRequest) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *SetVHostsRequest) GetVhosts() []string {
	if m != nil {
		return m.Vhosts
	}
	return nil
}

type SetAdditionalLabelsRequest struct {
	AppName          string            `protobuf:"bytes,1,opt,name=app_name,json=appName" json:"app_name,omitempty"`
	AdditionalLabels map[string]string `protobuf:"bytes,2,rep,name=additional_labels,json=additionalLabels" json:"additional_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *SetAdditionalLabelsRequest) Reset()                    { *m = SetAdditionalLabelsRequest{} }
func (m *SetAdditionalLabelsRequest) String() string            { return proto.CompactTextString(m) }
func (*SetAdditionalLabelsRequest) ProtoMessage()               {}
func (*SetAdditionalLabelsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *SetAdditionalLabelsRequest) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *SetAdditionalLabelsRequest) GetAdditionalLabels() map[string]string {
	if m != nil {
		return m.AdditionalLabels
	}
	return nil
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func init() {
	proto.RegisterType((*CreateRequest)(nil), "app.CreateRequest")
	proto.RegisterType((*CreateRequest_Limits)(nil), "app.CreateRequest.Limits")
	proto.RegisterType((*CreateRequest_Limits_LimitRangeQuantity)(nil), "app.CreateRequest.Limits.LimitRangeQuantity")
	proto.RegisterType((*CreateRequest_Autoscale)(nil), "app.CreateRequest.Autoscale")
	proto.RegisterType((*ListResponse)(nil), "app.ListResponse")
	proto.RegisterType((*ListResponse_App)(nil), "app.ListResponse.App")
	proto.RegisterType((*LogsRequest)(nil), "app.LogsRequest")
	proto.RegisterType((*LogsResponse)(nil), "app.LogsResponse")
	proto.RegisterType((*InfoRequest)(nil), "app.InfoRequest")
	proto.RegisterType((*InfoResponse)(nil), "app.InfoResponse")
	proto.RegisterType((*InfoResponse_Address)(nil), "app.InfoResponse.Address")
	proto.RegisterType((*InfoResponse_EnvVar)(nil), "app.InfoResponse.EnvVar")
	proto.RegisterType((*InfoResponse_Status)(nil), "app.InfoResponse.Status")
	proto.RegisterType((*InfoResponse_Status_Pod)(nil), "app.InfoResponse.Status.Pod")
	proto.RegisterType((*InfoResponse_Autoscale)(nil), "app.InfoResponse.Autoscale")
	proto.RegisterType((*InfoResponse_Limits)(nil), "app.InfoResponse.Limits")
	proto.RegisterType((*InfoResponse_Limits_LimitRangeQuantity)(nil), "app.InfoResponse.Limits.LimitRangeQuantity")
	proto.RegisterType((*SetEnvRequest)(nil), "app.SetEnvRequest")
	proto.RegisterType((*SetEnvRequest_EnvVar)(nil), "app.SetEnvRequest.EnvVar")
	proto.RegisterType((*UnsetEnvRequest)(nil), "app.UnsetEnvRequest")
	proto.RegisterType((*SetSecretRequest)(nil), "app.SetSecretRequest")
	proto.RegisterType((*SetSecretRequest_SecretFile)(nil), "app.SetSecretRequest.SecretFile")
	proto.RegisterType((*SetAutoscaleRequest)(nil), "app.SetAutoscaleRequest")
	proto.RegisterType((*SetAutoscaleRequest_Autoscale)(nil), "app.SetAutoscaleRequest.Autoscale")
	proto.RegisterType((*SetReplicasRequest)(nil), "app.SetReplicasRequest")
	proto.RegisterType((*DeleteRequest)(nil), "app.DeleteRequest")
	proto.RegisterType((*DeletePodsRequest)(nil), "app.DeletePodsRequest")
	proto.RegisterType((*ChangeTeamRequest)(nil), "app.ChangeTeamRequest")
	proto.RegisterType((*SetVHostsRequest)(nil), "app.SetVHostsRequest")
	proto.RegisterType((*SetAdditionalLabelsRequest)(nil), "app.SetAdditionalLabelsRequest")
	proto.RegisterType((*Empty)(nil), "app.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for App service

type AppClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*Empty, error)
	Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (App_LogsClient, error)
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
	SetEnv(ctx context.Context, in *SetEnvRequest, opts ...grpc.CallOption) (*Empty, error)
	UnsetEnv(ctx context.Context, in *UnsetEnvRequest, opts ...grpc.CallOption) (*Empty, error)
	List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListResponse, error)
	SetAutoscale(ctx context.Context, in *SetAutoscaleRequest, opts ...grpc.CallOption) (*Empty, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*Empty, error)
	SetReplicas(ctx context.Context, in *SetReplicasRequest, opts ...grpc.CallOption) (*Empty, error)
	DeletePods(ctx context.Context, in *DeletePodsRequest, opts ...grpc.CallOption) (*Empty, error)
	SetSecret(ctx context.Context, in *SetSecretRequest, opts ...grpc.CallOption) (*Empty, error)
	UnsetSecret(ctx context.Context, in *UnsetEnvRequest, opts ...grpc.CallOption) (*Empty, error)
	ChangeTeam(ctx context.Context, in *ChangeTeamRequest, opts ...grpc.CallOption) (*Empty, error)
	SetVHosts(ctx context.Context, in *SetVHostsRequest, opts ...grpc.CallOption) (*Empty, error)
	SetAdditionalLabels(ctx context.Context, in *SetAdditionalLabelsRequest, opts ...grpc.CallOption) (*Empty, error)
}

type appClient struct {
	cc *grpc.ClientConn
}

func NewAppClient(cc *grpc.ClientConn) AppClient {
	return &appClient{cc}
}

func (c *appClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/app.App/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (App_LogsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_App_serviceDesc.Streams[0], c.cc, "/app.App/Logs", opts...)
	if err != nil {
		return nil, err
	}
	x := &appLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type App_LogsClient interface {
	Recv() (*LogsResponse, error)
	grpc.ClientStream
}

type appLogsClient struct {
	grpc.ClientStream
}

func (x *appLogsClient) Recv() (*LogsResponse, error) {
	m := new(LogsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *appClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	out := new(InfoResponse)
	err := grpc.Invoke(ctx, "/app.App/Info", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) SetEnv(ctx context.Context, in *SetEnvRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/app.App/SetEnv", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) UnsetEnv(ctx context.Context, in *UnsetEnvRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/app.App/UnsetEnv", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := grpc.Invoke(ctx, "/app.App/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) SetAutoscale(ctx context.Context, in *SetAutoscaleRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/app.App/SetAutoscale", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/app.App/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) SetReplicas(ctx context.Context, in *SetReplicasRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/app.App/SetReplicas", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) DeletePods(ctx context.Context, in *DeletePodsRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/app.App/DeletePods", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) SetSecret(ctx context.Context, in *SetSecretRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/app.App/SetSecret", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) UnsetSecret(ctx context.Context, in *UnsetEnvRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/app.App/UnsetSecret", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) ChangeTeam(ctx context.Context, in *ChangeTeamRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/app.App/ChangeTeam", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) SetVHosts(ctx context.Context, in *SetVHostsRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/app.App/SetVHosts", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) SetAdditionalLabels(ctx context.Context, in *SetAdditionalLabelsRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/app.App/SetAdditionalLabels", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for App service

type AppServer interface {
	Create(context.Context, *CreateRequest) (*Empty, error)
	Logs(*LogsRequest, App_LogsServer) error
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
	SetEnv(context.Context, *SetEnvRequest) (*Empty, error)
	UnsetEnv(context.Context, *UnsetEnvRequest) (*Empty, error)
	List(context.Context, *Empty) (*ListResponse, error)
	SetAutoscale(context.Context, *SetAutoscaleRequest) (*Empty, error)
	Delete(context.Context, *DeleteRequest) (*Empty, error)
	SetReplicas(context.Context, *SetReplicasRequest) (*Empty, error)
	DeletePods(context.Context, *DeletePodsRequest) (*Empty, error)
	SetSecret(context.Context, *SetSecretRequest) (*Empty, error)
	UnsetSecret(context.Context, *UnsetEnvRequest) (*Empty, error)
	ChangeTeam(context.Context, *ChangeTeamRequest) (*Empty, error)
	SetVHosts(context.Context, *SetVHostsRequest) (*Empty, error)
	SetAdditionalLabels(context.Context, *SetAdditionalLabelsRequest) (*Empty, error)
}

func RegisterAppServer(s *grpc.Server, srv AppServer) {
	s.RegisterService(&_App_serviceDesc, srv)
}

func _App_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.App/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_Logs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AppServer).Logs(m, &appLogsServer{stream})
}

type App_LogsServer interface {
	Send(*LogsResponse) error
	grpc.ServerStream
}

type appLogsServer struct {
	grpc.ServerStream
}

func (x *appLogsServer) Send(m *LogsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _App_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.App/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_SetEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).SetEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.App/SetEnv",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).SetEnv(ctx, req.(*SetEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_UnsetEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsetEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).UnsetEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.App/UnsetEnv",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).UnsetEnv(ctx, req.(*UnsetEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.App/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).List(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_SetAutoscale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAutoscaleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).SetAutoscale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.App/SetAutoscale",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).SetAutoscale(ctx, req.(*SetAutoscaleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.App/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_SetReplicas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetReplicasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).SetReplicas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.App/SetReplicas",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).SetReplicas(ctx, req.(*SetReplicasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_DeletePods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).DeletePods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.App/DeletePods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).DeletePods(ctx, req.(*DeletePodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_SetSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).SetSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.App/SetSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).SetSecret(ctx, req.(*SetSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_UnsetSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsetEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).UnsetSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.App/UnsetSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).UnsetSecret(ctx, req.(*UnsetEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_ChangeTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).ChangeTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.App/ChangeTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).ChangeTeam(ctx, req.(*ChangeTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_SetVHosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetVHostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).SetVHosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.App/SetVHosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).SetVHosts(ctx, req.(*SetVHostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_SetAdditionalLabels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAdditionalLabelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).SetAdditionalLabels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.App/SetAdditionalLabels",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).SetAdditionalLabels(ctx, req.(*SetAdditionalLabelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _App_serviceDesc = grpc.ServiceDesc{
	ServiceName: "app.App",
	HandlerType: (*AppServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _App_Create_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _App_Info_Handler,
		},
		{
			MethodName: "SetEnv",
			Handler:    _App_SetEnv_Handler,
		},
		{
			MethodName: "UnsetEnv",
			Handler:    _App_UnsetEnv_Handler,
		},
		{
			MethodName: "List",
			Handler:    _App_List_Handler,
		},
		{
			MethodName: "SetAutoscale",
			Handler:    _App_SetAutoscale_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _App_Delete_Handler,
		},
		{
			MethodName: "SetReplicas",
			Handler:    _App_SetReplicas_Handler,
		},
		{
			MethodName: "DeletePods",
			Handler:    _App_DeletePods_Handler,
		},
		{
			MethodName: "SetSecret",
			Handler:    _App_SetSecret_Handler,
		},
		{
			MethodName: "UnsetSecret",
			Handler:    _App_UnsetSecret_Handler,
		},
		{
			MethodName: "ChangeTeam",
			Handler:    _App_ChangeTeam_Handler,
		},
		{
			MethodName: "SetVHosts",
			Handler:    _App_SetVHosts_Handler,
		},
		{
			MethodName: "SetAdditionalLabels",
			Handler:    _App_SetAdditionalLabels_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Logs",
			Handler:       _App_Logs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/protobuf/app/app.proto",
}

func init() { proto.RegisterFile("pkg/protobuf/app/app.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0x5f, 0x73, 0xdb, 0x44,
	0x10, 0x1f, 0xc5, 0xb6, 0x6c, 0xaf, 0x53, 0x9a, 0x1c, 0x69, 0x50, 0xd4, 0x32, 0xa4, 0x62, 0x3a,
	0x63, 0x68, 0x71, 0x4d, 0x5a, 0x86, 0xd2, 0xa7, 0x86, 0xd6, 0x1d, 0x3a, 0x64, 0x98, 0x22, 0x27,
	0x7d, 0xd5, 0x5c, 0xec, 0x4b, 0xaa, 0xa9, 0x2c, 0x5d, 0x75, 0x27, 0xd1, 0x30, 0x7c, 0x03, 0xbe,
	0x06, 0x5f, 0x84, 0x67, 0xde, 0x78, 0xe1, 0xb1, 0x7c, 0x07, 0x86, 0x77, 0xe6, 0xfe, 0xe8, 0x6f,
	0x64, 0x37, 0x65, 0xa0, 0x0f, 0x1e, 0xdf, 0xee, 0xed, 0xee, 0xed, 0xad, 0xf6, 0xf7, 0xbb, 0x05,
	0x9b, 0xbe, 0x38, 0xbd, 0x4d, 0xe3, 0x88, 0x47, 0xc7, 0xc9, 0xc9, 0x6d, 0x4c, 0xa9, 0xf8, 0x8d,
	0xa4, 0x02, 0xb5, 0x30, 0xa5, 0xce, 0x6f, 0x26, 0x5c, 0x7a, 0x18, 0x13, 0xcc, 0x89, 0x4b, 0x5e,
	0x26, 0x84, 0x71, 0x84, 0xa0, 0x1d, 0xe2, 0x05, 0xb1, 0x8c, 0x5d, 0x63, 0xd8, 0x77, 0xe5, 0x5a,
	0xe8, 0x38, 0xc1, 0x0b, 0x6b, 0x4d, 0xe9, 0xc4, 0x1a, 0x5d, 0x87, 0x75, 0x1a, 0x47, 0x33, 0xc2,
	0x98, 0xc7, 0xcf, 0x28, 0xb1, 0x5a, 0x72, 0x6f, 0xa0, 0x75, 0x87, 0x67, 0x94, 0xa0, 0xcf, 0xc1,
	0x0c, 0xfc, 0x85, 0xcf, 0x99, 0xd5, 0xde, 0x35, 0x86, 0x83, 0xbd, 0x9d, 0x91, 0x38, 0xbd, 0x72,
	0xdc, 0xe8, 0x40, 0x1a, 0xb8, 0xda, 0x10, 0xdd, 0x87, 0x3e, 0x4e, 0x78, 0xc4, 0x66, 0x38, 0x20,
	0x56, 0x47, 0x7a, 0x5d, 0x6b, 0xf0, 0xda, 0xcf, 0x6c, 0xdc, 0xc2, 0x5c, 0x64, 0x94, 0xfa, 0x31,
	0x4f, 0x70, 0xe0, 0x3d, 0x8f, 0x18, 0xb7, 0x4c, 0x95, 0x91, 0xd6, 0x7d, 0x13, 0x31, 0x8e, 0x6c,
	0xe8, 0xf9, 0x21, 0x27, 0x71, 0x88, 0x03, 0xab, 0xbb, 0x6b, 0x0c, 0x7b, 0x6e, 0x2e, 0x8b, 0x3d,
	0x59, 0x98, 0x59, 0x14, 0x58, 0x3d, 0xe9, 0x9a, 0xcb, 0xe8, 0x53, 0xd8, 0x8c, 0x09, 0x23, 0x71,
	0x4a, 0x3c, 0xc6, 0x31, 0xf7, 0x67, 0x9e, 0x4f, 0xad, 0xbe, 0x0c, 0x70, 0x59, 0x6f, 0x4c, 0xa5,
	0xfe, 0x09, 0x45, 0x47, 0xb0, 0x89, 0xe7, 0x73, 0x9f, 0xfb, 0x51, 0x88, 0x03, 0x2f, 0xc0, 0xc7,
	0x24, 0x60, 0x16, 0xec, 0xb6, 0x86, 0x83, 0xbd, 0x61, 0xd3, 0x55, 0x72, 0xdb, 0x03, 0x69, 0x3a,
	0x09, 0x79, 0x7c, 0xe6, 0x6e, 0xe0, 0x9a, 0xda, 0xfe, 0xdb, 0x00, 0x53, 0x15, 0x0b, 0x3d, 0x86,
	0xee, 0x9c, 0x9c, 0xe0, 0x24, 0xe0, 0x96, 0x21, 0xe3, 0xde, 0x5a, 0x5a, 0x58, 0xf5, 0xe7, 0xe2,
	0xf0, 0x94, 0x7c, 0x9f, 0xe0, 0x90, 0xfb, 0xfc, 0xcc, 0xcd, 0x9c, 0xd1, 0x11, 0x5c, 0xd6, 0x4b,
	0x2f, 0x56, 0x5e, 0xd6, 0xda, 0xbf, 0x88, 0xf7, 0x9e, 0x0e, 0xa2, 0x2d, 0xed, 0x03, 0x40, 0xe7,
	0xad, 0x44, 0x79, 0x5f, 0xea, 0xb5, 0xee, 0xad, 0x5c, 0x16, 0x7b, 0x31, 0x61, 0x51, 0x12, 0xcf,
	0x88, 0xee, 0xb1, 0x5c, 0xb6, 0x09, 0xf4, 0xf3, 0xaf, 0x8d, 0xee, 0xc2, 0xf6, 0x8c, 0x26, 0x1e,
	0xc7, 0xf1, 0x29, 0xe1, 0x5e, 0xc2, 0xfd, 0xc0, 0xff, 0x11, 0x8b, 0x32, 0xc9, 0x90, 0x1d, 0x77,
	0x6b, 0x46, 0x93, 0x43, 0xb9, 0x79, 0x54, 0xec, 0xa1, 0x0d, 0x68, 0x2d, 0xf0, 0x2b, 0x19, 0xb9,
	0xe3, 0x8a, 0xa5, 0xd4, 0xf8, 0xa1, 0xec, 0x59, 0xa1, 0xf1, 0x43, 0xfb, 0x21, 0x5c, 0x69, 0xfc,
	0x12, 0xc2, 0xf4, 0x05, 0xc9, 0x52, 0x16, 0x4b, 0xb4, 0x05, 0x9d, 0x14, 0x07, 0x49, 0x96, 0xaa,
	0x12, 0xee, 0xaf, 0xdd, 0x33, 0x9c, 0x9f, 0x60, 0xfd, 0xc0, 0x67, 0xdc, 0x25, 0x8c, 0x46, 0x21,
	0x23, 0xe8, 0x13, 0x68, 0x63, 0x4a, 0x99, 0xfe, 0x4a, 0x57, 0x64, 0x55, 0xcb, 0x06, 0xa3, 0x7d,
	0x4a, 0x5d, 0x69, 0x62, 0xef, 0x43, 0x6b, 0x9f, 0xd2, 0x1c, 0x69, 0x46, 0x09, 0x69, 0x19, 0x22,
	0xd7, 0xaa, 0x88, 0x4c, 0xe2, 0x80, 0x59, 0xad, 0xdd, 0x96, 0xd0, 0x89, 0xb5, 0xf3, 0x8b, 0x01,
	0x83, 0x83, 0xe8, 0x94, 0xad, 0x42, 0xf2, 0x16, 0x74, 0x02, 0x3f, 0x24, 0x4c, 0x06, 0x6b, 0xb9,
	0x4a, 0x40, 0xdb, 0x60, 0x9e, 0x44, 0x41, 0x10, 0xfd, 0x20, 0x2b, 0xd2, 0x73, 0xb5, 0x84, 0x76,
	0xa0, 0x47, 0xa3, 0xb9, 0x27, 0xa3, 0xb4, 0x65, 0x94, 0x2e, 0x8d, 0xe6, 0xdf, 0x89, 0x40, 0x12,
	0x2d, 0x24, 0xf5, 0xa3, 0x84, 0x49, 0x9c, 0xf6, 0xdc, 0x5c, 0x46, 0xd7, 0xa0, 0x3f, 0x8b, 0x42,
	0x8e, 0xfd, 0x90, 0xc4, 0x1a, 0x85, 0x85, 0xc2, 0x71, 0x60, 0x5d, 0x65, 0xa9, 0x8b, 0x24, 0xaf,
	0xfc, 0x8a, 0x17, 0x57, 0x7e, 0xc5, 0x9d, 0xeb, 0x30, 0x78, 0x12, 0x9e, 0x44, 0x2b, 0x6e, 0xe2,
	0xbc, 0xee, 0xc2, 0xba, 0xb2, 0x29, 0xc7, 0xa9, 0x95, 0xee, 0x4b, 0xe8, 0xe3, 0xf9, 0x3c, 0x26,
	0x8c, 0xc9, 0x2b, 0xb7, 0x72, 0x12, 0x2a, 0x7b, 0x0a, 0x08, 0x0a, 0x13, 0xb7, 0xb0, 0x45, 0x77,
	0xa0, 0x47, 0xc2, 0xd4, 0x4b, 0x71, 0xac, 0x6a, 0x3c, 0xd8, 0xb3, 0xce, 0xfb, 0x4d, 0xc2, 0xf4,
	0x19, 0x8e, 0xdd, 0x2e, 0x91, 0xff, 0x0c, 0x8d, 0xc1, 0x14, 0xec, 0x90, 0x64, 0x7c, 0xd7, 0xe0,
	0x32, 0x95, 0xfb, 0xae, 0xb6, 0x43, 0x5f, 0x9d, 0xa7, 0xbb, 0xab, 0x0d, 0xf9, 0x35, 0xb1, 0xdd,
	0x38, 0x27, 0x57, 0x73, 0xd9, 0x61, 0x35, 0x6e, 0x2d, 0x13, 0x5c, 0xb7, 0x46, 0x70, 0x16, 0x74,
	0xd3, 0x28, 0x48, 0x16, 0x84, 0x59, 0x3d, 0xd9, 0x52, 0x99, 0x68, 0xdf, 0x80, 0xae, 0xae, 0x8f,
	0x08, 0x20, 0x88, 0xb5, 0xf4, 0x29, 0x72, 0xd9, 0x1e, 0x83, 0xa9, 0xca, 0x71, 0x51, 0xc0, 0xd8,
	0xbf, 0x1a, 0x60, 0xaa, 0x72, 0x08, 0x97, 0x19, 0x4d, 0x34, 0x86, 0xc5, 0x12, 0x8d, 0xa1, 0x4d,
	0xa3, 0x79, 0x56, 0xfb, 0x6b, 0xcb, 0x0a, 0x39, 0x7a, 0x1a, 0xcd, 0x5d, 0x69, 0x69, 0x33, 0x68,
	0x3d, 0x8d, 0xe6, 0xcb, 0x9a, 0x5e, 0xd4, 0x3b, 0x3f, 0x5f, 0x0a, 0xe2, 0x50, 0x7c, 0xaa, 0xde,
	0xad, 0x96, 0x2b, 0x96, 0x9a, 0x86, 0x38, 0x8e, 0xf5, 0x8b, 0xd5, 0x71, 0x73, 0x59, 0xc4, 0x88,
	0x09, 0x9e, 0x9f, 0xe9, 0x66, 0x57, 0xc2, 0xbb, 0x22, 0xa7, 0xbf, 0x0a, 0xee, 0x9f, 0xd4, 0xb9,
	0xff, 0xe6, 0xb2, 0xef, 0xbe, 0x92, 0xfa, 0x0f, 0x97, 0x51, 0xff, 0x5b, 0x85, 0xfb, 0x5f, 0x99,
	0xdf, 0xf9, 0xd9, 0x80, 0x4b, 0x53, 0xc2, 0x27, 0x61, 0xba, 0x8a, 0xd1, 0xee, 0x96, 0x90, 0x5a,
	0x46, 0x78, 0xc5, 0xb3, 0x0e, 0xd5, 0xb7, 0x6f, 0x57, 0xe7, 0x01, 0x5c, 0x3e, 0x0a, 0xd9, 0x1b,
	0xd3, 0xd9, 0xa9, 0xa5, 0xd3, 0xcf, 0xcf, 0x74, 0x5e, 0x1b, 0xb0, 0x31, 0x25, 0x7c, 0x4a, 0x66,
	0x31, 0xe1, 0xab, 0x62, 0xdc, 0x87, 0x01, 0x93, 0x46, 0x1e, 0x09, 0xd3, 0x0b, 0xdc, 0x0a, 0x94,
	0xf5, 0x24, 0x4c, 0x19, 0xda, 0xcf, 0x7d, 0x4f, 0xfc, 0x40, 0x75, 0xf7, 0x60, 0x6f, 0x37, 0xf3,
	0xad, 0x9c, 0x3d, 0x52, 0xd2, 0x63, 0x3f, 0x20, 0x59, 0x08, 0xb1, 0xb6, 0xef, 0x01, 0x14, 0x3b,
	0x0d, 0xf5, 0xb1, 0xa0, 0x2b, 0xd8, 0x9c, 0x84, 0x5c, 0x56, 0x68, 0xdd, 0xcd, 0x44, 0xe7, 0x77,
	0x03, 0xde, 0x9f, 0x12, 0x5e, 0xf0, 0xd5, 0x8a, 0x4b, 0x3e, 0x28, 0x53, 0xdf, 0x9a, 0x4c, 0xd3,
	0xc9, 0xd2, 0xac, 0x07, 0x68, 0x64, 0xc0, 0x77, 0x04, 0x3e, 0xe7, 0x11, 0xa0, 0xa9, 0xa8, 0x19,
	0x0d, 0xfc, 0x19, 0x5e, 0xf9, 0xb8, 0xca, 0x66, 0x56, 0x66, 0x3a, 0x64, 0x2e, 0x3b, 0x1f, 0xc3,
	0xa5, 0x47, 0x24, 0x20, 0x2b, 0xe7, 0x6c, 0xe7, 0x31, 0x6c, 0x2a, 0xa3, 0xa7, 0xd1, 0x7c, 0xe5,
	0x49, 0x1f, 0x02, 0x08, 0xd2, 0x93, 0x2f, 0x73, 0xd6, 0x67, 0x7d, 0xa1, 0x11, 0x6f, 0x33, 0x73,
	0xbe, 0x85, 0xcd, 0x87, 0xcf, 0x05, 0x06, 0x0f, 0x09, 0x5e, 0x64, 0x71, 0x76, 0xa0, 0x87, 0x29,
	0xf5, 0x4a, 0xb1, 0xba, 0x98, 0x52, 0xf9, 0x98, 0x5f, 0x85, 0xbe, 0x78, 0x2e, 0xbd, 0xd2, 0x98,
	0xd1, 0x13, 0x0a, 0xb1, 0xe9, 0x4c, 0x64, 0xd7, 0x3e, 0x13, 0xf3, 0x33, 0xbb, 0x40, 0xac, 0x6d,
	0x30, 0x53, 0xf1, 0x2a, 0x64, 0x69, 0x69, 0xc9, 0xf9, 0xd3, 0x00, 0x5b, 0x7c, 0xda, 0xda, 0x90,
	0x75, 0x81, 0x88, 0xc7, 0x4d, 0x03, 0xb5, 0x02, 0xc5, 0x17, 0x79, 0xc7, 0x34, 0x87, 0xbd, 0xf0,
	0x74, 0xfd, 0x9f, 0x8c, 0x7f, 0x5d, 0xe8, 0x4c, 0x16, 0x94, 0x9f, 0xed, 0xfd, 0xd1, 0x51, 0xd3,
	0xdc, 0x10, 0x4c, 0x35, 0x44, 0x23, 0x74, 0x7e, 0xa2, 0xb6, 0x41, 0xea, 0xa4, 0x07, 0xfa, 0x0c,
	0xda, 0x62, 0x28, 0x42, 0x1b, 0x6a, 0x46, 0x2c, 0xa6, 0x38, 0x7b, 0xb3, 0xa4, 0x51, 0x84, 0x3c,
	0x36, 0xd0, 0x4d, 0x68, 0x0b, 0x8a, 0xd6, 0xe6, 0xa5, 0x51, 0x49, 0x9b, 0x57, 0x06, 0xa3, 0x21,
	0x98, 0x8a, 0x36, 0x74, 0x16, 0x15, 0x0e, 0xa9, 0x64, 0x71, 0x0b, 0x7a, 0x19, 0xc7, 0xa1, 0x2d,
	0xa9, 0xaf, 0x51, 0x5e, 0xc5, 0xfa, 0x06, 0xb4, 0xc5, 0x30, 0x8b, 0x4a, 0xba, 0x2c, 0xdb, 0xf2,
	0x10, 0x7c, 0x17, 0xd6, 0xcb, 0x90, 0x46, 0xd6, 0x32, 0x94, 0x57, 0x82, 0x0f, 0xc1, 0x54, 0x50,
	0xd0, 0x49, 0x57, 0xc0, 0x53, 0xb1, 0xdc, 0x83, 0x41, 0x09, 0x9f, 0xe8, 0x83, 0x2c, 0x7c, 0x0d,
	0xb1, 0x15, 0x9f, 0x31, 0x40, 0x01, 0x34, 0xb4, 0x5d, 0x3a, 0xa1, 0x84, 0xbc, 0x8a, 0xc7, 0x08,
	0xfa, 0x39, 0x7f, 0xa2, 0x2b, 0x8d, 0x7c, 0x5a, 0xb1, 0xbf, 0x0d, 0x03, 0x59, 0x3b, 0xed, 0xf1,
	0xe6, 0x6a, 0x8e, 0x01, 0x0a, 0xcc, 0xea, 0x94, 0xce, 0x81, 0xb8, 0x21, 0x25, 0x05, 0xcc, 0x22,
	0xa5, 0x0a, 0x50, 0x2b, 0xf6, 0x5f, 0x2b, 0x72, 0xae, 0xb5, 0x39, 0xfa, 0xe8, 0x0d, 0x18, 0x2a,
	0xc7, 0x38, 0x36, 0xe5, 0xc4, 0x78, 0xe7, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xea, 0x15, 0xe6,
	0x1f, 0x59, 0x10, 0x00, 0x00,
}
